11 support strykerjs to be ran with this action (#16)
* test if composite can run docker container

* update to right image

* revert to local docker image

* run local docker image

* some other test

* run local docker image

* does this work?

* temp test

* update

* update arg ref

* test for public package

* test for public package

* chmod stuff;

* removed html reporter

* update docker image with arguments

* does this work?

* use github workspace

* update

* mount github workspace inside of container

* shell is mandatory

* update

* changed target of mount to base

* added LS to see what happens....

* list directory

* update

* update

* update

* update

* update

* update

* update

* update

* added workspace to testporject ref

* removed ls command

* update dockerfile stuff;

* renamed stryker.net dockerfile

* update

* update

* update

* update

* update packge reference

* remove not working stuff;

* added stryker version

* update

* update readme

* update input parameter name

* update base image name

* added strykerJS base image

* bring back the html report

* run strykerJS config

* run strykerJS from the pipeline

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -5,17 +5,43 @@ branding:
   icon: 'zap'
   color: 'red'
 inputs:
+  tool:
+    description: "The type of stryker that you want to run (accepted values: Stryker.NET)"
+    required: true
   testProject:
     description: "The path to the test project directory (e.g. BusinessLogic.Test/)"
     required: true
-  breakAt:
-    description: "When threshold break is set to anything other than 0 and the mutation score is lower than the threshold Stryker will exit with a non-zero code."
+  configFile:
+    description: "The path to the stryker config file"
     required: false
-    default: "0"
+    default: ./
 
 runs:
-  using: 'docker'
-  image: 'run-stryker-net.dockerfile'
-  args:
-    - ${{ inputs.testProject }}
-    - ${{ inputs.breakAt }}
+  using: "composite"
+  steps:
+    - name: Check tool
+      if: ${{ inputs.tool != 'Stryker.NET' }}
+      run: |
+        echo "Invalid tool. Expected 'Stryker.NET' or StrykerJS."
+        exit 1
+      shell: bash 
+
+    - name: Run Stryker.NET
+      if: ${{ inputs.tool == 'Stryker.NET' }}
+      shell: bash
+      run: | 
+        docker run \
+          -v ${{ github.workspace }}:/workspace \
+          ghcr.io/stryker-mutator/run-stryker-net:11-support-strykerjs-to-be-ran-with-this-action \
+          /workspace/${{ inputs.testProject }} \
+          ${{ inputs.configFile }}  \
+          
+    - name: Run StrykerJS
+      if: ${{ inputs.strykerVersion == 'StrykerJS' }}
+      shell: bash
+      run: | 
+        docker run \
+          -v ${{ github.workspace }}:/workspace \
+          ghcr.io/stryker-mutator/run-strykerjs:11-support-strykerjs-to-be-ran-with-this-action \
+          /workspace/${{ inputs.testProject }} \
+          ${{ inputs.configFile }}  \
